config/routes.rb
Rails.application.routes.draw do
  # get 'homes/index'
  
  resources :buses

  authenticate :user, lambda { |u| u.admin? } do
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  end
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users do
    resources :buses do
      post 'reservations/create/:user_id', to: 'reservations#create'
    end
  end

  authenticate :user do
    resources :reservations
  end
  # resources :bus_owners do
  #   resources :buses
  # end


  get '/logout', to: 'sessions#destroy', as: :logout
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "homes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bus.rb
class Bus < ApplicationRecord
  serialize :booked_seats, Array
  serialize :available_seats, Array
  SOURCE = ['New Delhi', 'Lucknow', 'Kanpur', 'Haridwar', 'Varanasi']
  DESTINATION = ['New Delhi', 'Lucknow', 'Kanpur', 'Haridwar', 'Varanasi']

  attr_accessor :source, :destination
  enum status: [:pending, :approved, :rejected]

  before_save :strip_name_whitespace
  has_many :reservations

  validates :name, presence: true
  validates :registration_no, presence: true
  validates :source_route, presence: true
  validates :destination_route, presence: true
  validates :no_of_seats, presence: true
  validates :status, presence: true

  scope :approved, -> { where(status: 'approved') }

  def self.search(source, destination, bus_name)
    if source&.present? && destination&.present? && bus_name.present? 
      where("source_route LIKE ? AND destination_route LIKE ? AND name LIKE?", "#{source}", "#{destination}", "#{bus_name}")
    elsif source.present? && destination.present?
      where("source_route LIKE ? AND destination_route LIKE ?", "#{source}", "#{destination}")
    else
      where("name LIKE?", "#{bus_name}")
    end
  end

  private

  def strip_name_whitespace
    self.name = name.strip
  end
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	serialize :booked_seats, Array
  serialize :available_seats, Array

  enum status: [:cash, :upi]
	belongs_to :user
	belongs_to :bus

	# validates :reservation_date, presence: true
  # validates :no_of_seats, presence: true, numericality: { greater_than: 0 }

  # validate :available_seats

  # def available_seats
  #   if bus.reservations.where(reservation_date: reservation_date).sum(:no_of_seats) + no_of_seats > bus.no_of_seats
  #     errors.add(:no_of_seats, "is not available")
  #   end
  # end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:customer, :admin, :bus_owner]

  scope :bus_owners, -> { where(role: "bus_owner") }

  has_many :reservations
  has_many :buses, class_name: "Bus", foreign_key: "bus_owner_id"

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?, only: [:create]
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    if resource.admin?
      rails_admin_path # or any other admin page path
    else
      root_path # or any other default page path
    end
  end

  protected

  def configure_permitted_parameters
    if params["user"]["role"] == "0"
    	params["user"]["role"] = "customer"
    	attributes = [:role]
    	devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    else
    	attributes = [:role]
    	devise_parameter_sanitizer.permit(:sign_up, keys: attributes)

    end
	end
end

app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :authenticate_bus_owner!, only: [:index, :new, :create, :edit, :update, :destroy]
  before_action :set_bus, only: [:edit, :update, :destroy]

  def index
    @home_show_link = true
    @buses = current_user.buses
  end

  def new
    @home_show_link = true
    @bus = Bus.new
  end

  def create
    debugger
    @bus = Bus.new(bus_params)
    @bus.bus_owner_id = current_user.id

    if @bus.save
      redirect_to buses_path
    else
      render :new
    end
  end

  # def create
  #   @bus = current_user.buses.build(bus_params)

  #   if @bus.save
  #     redirect_to @bus
  #   else
  #     render :new
  #   end
  # end



  def show
    @bus = Bus.find(params[:id])
  end

  def edit
  end

  def update
    if @bus.update(bus_params)
      redirect_to buses_path
    else
      render :edit
    end
  end

  def destroy
    @bus.destroy
    redirect_to buses_path
  end

  private

  def authenticate_bus_owner!
    unless current_user && current_user.bus_owner?
      redirect_to root_path, alert: "You don't have permission to access this page"
    end
  end

  def set_bus
    @bus = current_user.buses.find(params[:id])
  end


  def bus_params
    params.require(:bus).permit(:name, :registration_no, :source_route, :destination_route, :fare, :status, :no_of_seats, :bus_owner_id, { booked_seats: [] }, {available_seats: []})
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @show_link = true
    @buses = Bus.approved

    session[:name] = params[:name]
    session[:source_route] = params[:source_route]
    session[:destination_route] = params[:destination_route]

    @buses = @buses.search(params[:source_route], params[:destination_route], params[:name])if params[:source_route].present? && params[:destination_route].present? || params[:name].present?
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_bus_owner!, only: [:index, :new, :destroy]
  before_action :authenticate_user!

  def new
  end
  
  def index
    @reservations = Reservation.includes(:bus, :user).all.order(reservation_date: :desc)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      respond_to do |format|
        format.html # renders index.html.erb
        format.json { render json: { success: true } } # renders JSON format
      end
      ReservationMailer.booking_confirmation(@reservation).deliver_now
    else
      render json: { success: false }
    end
  end

  def show
    @reservation = Reservation.find(params[:id]).order(reservation_date: :desc)
  end

  def user_reservations
    reservations = Reservation.where(user_id: params[:id])
    @reservations = reservations.includes(:bus, :user).all.order(reservation_date: :desc)
    render 'user_reservations'
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
    redirect_to reservations_path, notice: "Reservation cancelled successfully."
  end

  def cancel_reservation
    @reservation = Reservation.find(params[:reservation_id])
    ReservationMailer.cancel_reservation(@reservation).deliver_now
    @reservation.destroy
    redirect_to "/#{params[:id]}/reservations", notice: "Reservation cancelled successfully."
  end

  private

  def reservation_params
    params.require(:reservation).permit(:user_id, :bus_id, :reservation_date, :available_seats => [], :booked_seats => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def destroy
    sign_out(current_user)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buses_helper.rb
module BusesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/buses/_bus.html.erb
<div id="<%= dom_id bus %>">
  <button type="button" id="busModal" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#myModal" data-bus-id="<%= bus&.id %>" data-user-id="<%= current_user&.id %>" onclick="bookSeat()">Book Your Seat</button>
</div>

app/views/buses/_form.html.erb
<%= form_with(model: bus) do |form| %>
  <% if bus&.errors&.any? %>
    <div style="color: red">
      <h2><%= pluralize(bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
        <% bus&.errors&.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Bus_Name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :source_route, style: "display: block" %>
    <%= form.select :source_route, options_for_select(Bus::SOURCE), {}, {class: "form-control"} %>
  </div>

  <div>
    <%= form.label :destination_route, style: "display: block" %>
    <%= form.select :destination_route, options_for_select(Bus::DESTINATION), {}, {class: "form-control"} %>
  </div>

  <div>
    <%= form.label :registration_no, style: "display: block" %>
    <%= form.text_field :registration_no %>
  </div>

  <div>
    <%= form.label :no_of_seats_in_bus, style: "display: block" %>
    <%= form.number_field :no_of_seats %>
  </div>

  <div>
    <%= form.label :fare, style: "display: block" %>
    <%= form.text_field :fare %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

  <!-- if bus_owner want to mention available seats -->
  <div>
    <%#= form.label :available_seats, style: "display: block" %>
    <%#= form.text_field :available_seats %>
    

  </div>

  <!-- if bus_owner want to mention booked_seats for themself first-->
  <div>
    <%= form.label :booked_seats, style: "display: block" %>
    <%= form.text_field :booked_seats %>
  </div>

  <div>
    <%= form.hidden_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/buses/edit.html.erb
<div class="container">
  <%= render "layouts/header" %>
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-12">
      <div class="card p-4"><h2>Editing bus</h2>

        <%= render "form", bus: @bus %>

        <br>

        <div>
          <%= link_to "Show this bus", @bus %> |
          <%= link_to "Back to buses", buses_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buses/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <%= render "layouts/header" %>
  <div>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Sr No.</th>
          <th scope="col">Bus Name</th>
          <th scope="col">Source Route</th>
          <th scope="col">Destination Route</th>
          <th scope="col">No Of Seats</th>
          <th scope="col">Registration No</th>
          <%if current_user&.role == "bus_owner"%><th scope="col">Status</th><% end %>
          <th scope="col">Fare</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @buses&.each_with_index do |bus, i| %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= bus.name %></td>
            <td><%= bus.source_route %></td>
            <td><%= bus.destination_route %></td>
            <td><%= bus.no_of_seats %></td>
            <td><%= bus.registration_no %></td>
            <td scope="col"><span style="color: <%= bus.status == 'pending' ? 'yellow' : bus.status == 'rejected' ? 'red' : 'green' %>;"><%= bus.status %></span></td>
            <td><%= bus.fare %></td>
            <td colspan="2" class="btn-group"><%= link_to "Edit", edit_bus_path(bus.id), class: "btn btn-secondary" %>  <%= button_to "Delete", bus_path(bus.id), method: :delete, class: "btn btn-danger" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/buses/new.html.erb
<div class="container">
  <%= render "layouts/header" %>
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-12">
      <div class="card p-4">

        <%= render "form", bus: @bus %>

        <br>

        <div>
          <%= link_to "Back to buses", buses_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/buses/show.html.erb
<!-- <p style="color: green"><%#= notice %></p> -->

<div class="container pt-4 pb-4">
  <div class="d-flex align-items-center justify-content-between">
    <h4>Book Your seat here...</h4>
    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
  </div>
  <hr>
  <div class="row">
    <!-- ab = <%# @bus.&no_of_seats%> -->
    <%1.upto(20) do |a| %>
      <div class="col-md-3">
        <div class="text-center">
          <i class="fas fa-couch"></i>
          <i class="fas fa-couch" style="color: red <%#= couch_selected ? 'red' : 'inherit' %>"></i>
          <p style="font-size: 10px;color: gray;"><%= a %></p>
        </div>
      </div>
    <% end %>
  </div>
  <hr>
  <div class="d-flex align-items-center justify-content-between">
    <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
    <button type="button" id="busModal" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#myModal" data-bus-id="<%= @bus&.id %>" data-user-id="<%= current_user&.id %>" onclick="bookSeat()">Book Your Seat</button>

  </div>
</div>

app/views/buses/update_show.html.erb
<div class="modal-body">
	<div class="container">
    <div class="d-flex align-items-center justify-content-between">
      <h4>Choose Your Seat</h4>
      <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
    </div>
		<div id="available-seats-section">
		  <div class="row">
		      <% seats = @available_seats + @booked_seats %>
		      <% seats.sort.each do |seat| %>
		        <div class="col-md-3">
		          <div class="text-center">
		            <% selected = @booked_seats.include?(seat) %>
		            <label class="seat-label" style="color: <%= selected ? 'red' : 'inherit' %>">
		              <input type="checkbox" name="selected_seats[]" value="<%= seat %>" class="seat-checkbox"  <%= selected ? 'disabled' : '' %>>
		              <i class="fas fa-couch"></i><div class="font-text text-black-50" style="font-size: 10px;">seat no. <%= seat%></div>
		            </label>
		          </div>
		        </div>
		      <% end %>
		      <!-- <div class="form-group">
		        <label for="my-date">Booking Date:</label>
		        <input type="date" id="my-date" name="my_date" min="<%= Date.today.to_s %>">
		      </div> -->
		    </div>
		</div>
	  <button type="button" id="busModal" class="btn btn-primary float-end" data-bs-toggle="modal" data-bs-target="#myModal" data-bus-id="<%= @bus&.id %>" data-user-id="<%= current_user&.id %>" onclick="reservation()">Book Your Seat 1</button>
	</div>
	<div class="modal-footer">
	  <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Back</button>
	</div>
</div>

<script>
	// Get the modal element
	var modal = document.querySelector('.modal');

	// Attach an event listener to the hidden.bs.modal event
	modal.addEventListener('hidden.bs.modal', function (event) {
	  // Reload the page
	  location.reload();
	});
</script>

app/views/homes/index.html.erb
<div class="container-fluid">
  <div class="header-section">
    <div class="image">
      <%= image_tag "bus_header.webp" %>
    </div>
    <h2>Bus Reservation System</h2>
  </div>
</div>
<div class="container mt-5">
  <%= render "layouts/header" %>
</div>
<div class="container search-section">
  <%= render "layouts/search" %>
</div>
<div class="container">
  <div>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Sr No.</th>
          <th scope="col">Bus Name</th>
          <th scope="col">Source Route</th>
          <th scope="col">Destination Route</th>
          <th scope="col">No Of Seats</th>
          <th scope="col">Registration No</th>
          <th scope="col">Fare</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <% @buses&.each_with_index do |bus, i| %>
          <tr>
            <th scope="row"><%= i+1 %></th>
            <td><%= bus.name %></td>
            <td><%= bus.source_route %></td>
            <td><%= bus.destination_route %></td>
            <td><%= bus.no_of_seats %></td>
            <td><%= bus.registration_no %></td>
            <td><%= bus.fare %></td>
            <td>
              <button type="button" id="productModal<%= i %>" class="btn btn-secondary" data-bs-toggle="modal" data-bs-target="#product-modal" data-bus-id="<%= bus&.id %>" onclick="bookSeat(<%= i %>)">Book Your Seat</button>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

<!-- Modal -->
<div class="modal fade" id="product-modal" tabindex="-1" role="dialog" aria-labelledby="product-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <!-- content of show.html.erb from buses -->
    </div>
  </div>
</div>

<div class="modal" id="myModal">
  <div class="modal-dialog">
     <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">
          Thanks for Reservation!
        </h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body">
        <p>We will look over your message and get back to you by tomorrow. In the meantime, you can check the FAQ section, look over our new product collection or browse through our latest blog posts [link to another page — will be displayed as Please click here to continue].

        Your can see your info on My booking section</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Close</button>
      </div>


<script>
// Handle the click event on the link
function bookSeat(index) {
    // Get the product ID from the link
    var productId = $('#productModal'+ index).data('bus-id');
    // Send an AJAX request to fetch the show page
    $.ajax({
      url: '/buses/' + productId,
      method: 'GET',
      success: function(response) {
        // Insert the response into the modal
        $('#product-modal .modal-content').html(response);
        $("#product-modal").modal("show");
      }
    });
  // });
}
</script>

<style type="text/css">
  .header-section{
    position: relative;
  }
  .header-section h2{
    position: absolute;
    top: 0;
    bottom: 0;
    top: 230px;
    left: 0;
    right: 0;
    text-align: center;
/*    z-index: 9999;*/
    font-size: 60px;
    color: white;
  }
  .search-section{
/*    position: absolute;*/
    top: 460px;
    bottom: 0;
    left: 0;
    right: 0;
    text-align: center;
  }
  .image{
    width: 100%;
    height: 500px;
    opacity: 0.5;
  }
  .image img{
    width: 100%;
    height: 100%;
    object-fit: cover;
  }
</style>

app/views/layouts/_alert.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.erb
<header>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top shadow">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarExample01">
      	<strong>Bus Reservation System</strong>
				<% if current_user %>
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
	            <a class="nav-link" href="#">
							Hello! <%= current_user.role %></a>
						</li>
					</ul>
					<ul class="navbar-nav ">
						<%if current_user.bus_owner? && @show_link%>
    					<%= link_to "List Of your Buses", buses_path, :class => "btn btn-light"%>
    					<li class="nav-item", style="margin-left: 10px;">
								<%= link_to "Add Bus", new_bus_path, :class => "btn btn-primary"%>
							</li>
						<%end%>
						<%if current_user.bus_owner? && @home_show_link%>
							<li class="nav-item", style="margin-left: 10px;">
								<%= link_to "Add Bus", new_bus_path, :class => "btn btn-primary"%>
							</li>
							<li class="nav-item" style="margin-left: 10px;">
								<%= link_to "Home", root_path, method: :delete, :class => "btn btn-primary" %>
							</li>
						<%end%>
						<li class="nav-item" style="margin-left: 10px;">
							<%#= link_to "Sign_out", destroy_user_session_path, method: :delete, :class => "btn btn-danger"%>
							<%= link_to "Logout", logout_path, method: :delete, :class => "btn btn-danger" %>
						</li>
					</ul>
				<% else %>
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item">
            <a class="nav-link" href="#">Hey! You are not signed in yet.</a>
						</li>
					</ul>
					<ul class="navbar-nav ">
						<li class="nav-item">
							<%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-secondary"%>
						</li>
						<li class="nav-item" style="margin-left: 10px;">
							<%= link_to "Login", new_user_session_path, :class => "btn btn-primary" %>
						</li>
					</ul>
				<% end %>
			</div>
    </div>
  </nav>
  <!-- Navbar -->
</header>

app/views/layouts/_search.html.erb
<%= form_tag root_path, class: "row bg-white p-5 shadow", method: :get do |f| %>
  <div class="col-md-3">
    <%= text_field_tag :name, session[:name], class: "form-control", placeholder: "Search bus name.." %>
  </div>
  <div class="col-md-3">
    <%#= label_tag :source_route, "Source" %>
    <%#= text_field_tag :source_route, session[:source_route] %>
    <%= select_tag :source_route, options_for_select(Bus::SOURCE, session[:source_route]), {prompt: "Select a source", class: "form-select", placeholder: "Choose a source"} %>
    </div>
  <div class="col-md-3">
    <%#= label_tag :destination_route, "Destination" %>
    <%#= text_field_tag :destination_route, session[:destination_route] %>
    <%= select_tag :destination_route, options_for_select(Bus::DESTINATION, session[:destination_route]), {prompt: "Select a destination", class: "form-select", placeholder: "Choose a destination"} %>
  </div>
  <div class="col-md-3">
    <%= submit_tag "Search", :class => "btn btn-light" %>
    <%= link_to "Clear", root_path, :class => "btn btn-danger"%>
  </div>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BusResevationSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/alert'%>
    <%= yield %>
  </body>
</html>

app/views/reservations/index.html.erb
<div class="container">
  <%= render "layouts/header" %>
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-12">
      <div class="card shadow p-5">
        <h2 class="text-center">Your Reservation Details</h2>
					<p><strong>Todal Bookings you have done: </strong><%= @reservations&.all&.count %></p>
				</div>
			</div>
		</div>
	<div class="row d-flex align-items-center justify-content-center">
		<div class="col-md-12">
			<% @reservations.each do |reservation|%>
      	<div class="card shadow p-5">
					<p><strong>Customer Name: </strong><%= reservation.user.email.gsub(/@gmail\.com/, "")%></p>
				  <span class="<%= reservation&.reservation_date < Date.today ? 'text-bg-success text-white' : 'text-bg-warning text-white' %> btn disabled">
					  <%= reservation&.reservation_date < Date.today ? 'Completed' : 'Upcoming trip' %>
					</span>
				  <p><strong>Bus: </strong><%=reservation.bus.id%></p>
				  <p><strong>Bus No. </strong><%= reservation&.bus&.registration_no %></p>
				  <% seat_numbers = reservation&.booked_seats.join(", ")%>
				  <p><strong>Seat No:</strong><%= seat_numbers%></p>
				  <p><strong>Reservation Date: </strong> <%= reservation&.reservation_date&.strftime("%B %d, %Y") %></p>
				  <p><strong>Source Route: </strong> <%= reservation&.bus&.source_route %></p>
				  <p><strong>Destination Route: </strong><%= reservation&.bus&.destination_route %></p>
				  <p>want to cancel reservation </p>
				  <!-- <span class="<%#= reservation&.reservation_date < Date.today ? 'disabled' : '' %>"><%#= button_to  "Cancel Reservation", reservation_path(reservation), method: :delete, data: { confirm: "Are you sure you want to cancel this reservation?"},class: (reservation&.reservation_date < Date.today ? "disabled" : "") %></span> -->
					<%= button_to "Cancel Reservation", reservation_path(reservation), method: :delete, data: { confirm: "Are you sure you want to cancel this reservation?" }, class: (reservation&.reservation_date < Date.today ? "disabled" : ""), disabled: (reservation&.reservation_date < Date.today) %>
				</div>

				<% end %>
		</div>
	</div>
</div>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>

<%= form_tag reservations_path do %>
  <% @seats.each do |seat| %>
    <div>
      <%= check_box_tag "seat_ids[]", seat.id %>
      <%= label_tag "seat_#{seat.id}", "Seat #{seat.number}" %>
    </div>
  <% end %>

  <%= submit_tag "Reserve Seats" %>
<% end %>

app/views/reservations/show.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <h2>All the info of your reserved seat!</h2>
</div>

app/views/reservations/user_reservations.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
  <%= render "layouts/header" %>
  <div class="row d-flex align-items-center justify-content-center">
    <div class="col-md-12">
      <h2>Your Reservation Details</h2>
      <p><strong>Todal Bookings you have done:</strong><%= @reservations.count %></p>
      <% @reservations.each do |reservation| %>
        <div class="card shadow p-5">
          <p><strong>Customer Name:</strong> <%= reservation&.user&.email.gsub(/@gmail\.com/, "") %></p>
          <span class="<%= reservation&.reservation_date < Date.today ? 'text-bg-success text-white' : 'text-bg-warning text-white' %> btn disabled">
            <%= reservation&.reservation_date < Date.today ? 'Completed' : 'Upcoming trip' %>
          </span>
          <p><strong>Bus No: </strong><%= reservation&.bus&.registration_no %></p>
          <% seat_numbers = reservation&.booked_seats.join(", ")%>
          <p><strong>Seat No: </strong><%= seat_numbers%></p>
          <p><strong>Reservation Date: </strong> <%= reservation&.reservation_date&.strftime("%B %d, %Y") %></p>
          <p><strong>Source Route: </strong> <%= reservation&.bus&.source_route %></p>
          <p><strong>Destination Route: </strong><%= reservation&.bus&.destination_route %></p>
          <p>want to cancel reservation</p>
          <td><%= button_to 'Cancel Reservation', destroy_reservation_path(id: current_user.id, reservation_id: reservation.id), method: :delete, data: { confirm: 'Are you sure you want to delete this reservation?' }, class: (reservation&.reservation_date < Date.today ? "disabled" : ""), disabled: (reservation&.reservation_date < Date.today) %></td>
        </div>
      <% end %>
    </div>
  </div>
</div>